jcornaz/kwik

- CHANGELOG.adoc
- core/src/commonMain/kotlin/com/github/jcornaz/kwik/Generator.kt
- core/src/commonMain/kotlin/com/github/jcornaz/kwik/Runner.kt
- core/src/commonMain/kotlin/com/github/jcornaz/kwik/Samples.kt
- core/src/commonTest/kotlin/com/github/jcornaz/kwik/CreateGeneratorTest.kt
- core/src/commonTest/kotlin/com/github/jcornaz/kwik/WithNullTest.kt
- core/src/commonTest/kotlin/com/github/jcornaz/kwik/WithSampleTest.kt
- core/src/commonTest/kotlin/com/github/jcornaz/kwik/runner/CheckForAll1Test.kt
- core/src/commonTest/kotlin/com/github/jcornaz/kwik/runner/ForAll1Test.kt
Provide `withSample` and `withNull` instead
> Remove edgeCase from `Generator`

- CHANGELOG.rst
- core/src/commonMain/kotlin/com/github/jcornaz/kwik/GeneratorOperators.kt
- core/src/commonTest/kotlin/com/github/jcornaz/kwik/operator/FilterTest.kt
- docs/contents.rst
- docs/operators.rst
> Add filter operator

- CHANGELOG.rst
- core/src/commonMain/kotlin/com/github/jcornaz/kwik/Runner.kt
- core/src/commonTest/kotlin/com/github/jcornaz/kwik/runner/ForAll1Test.kt
- core/src/commonTest/kotlin/com/github/jcornaz/kwik/runner/ForAll2Test.kt
- core/src/commonTest/kotlin/com/github/jcornaz/kwik/runner/ForAll3Test.kt
- core/src/commonTest/kotlin/com/github/jcornaz/kwik/runner/ForAll4Test.kt
> Improve error message in case of property falsification

- CHANGELOG.rst
- core/src/commonMain/kotlin/com/github/jcornaz/kwik/PropertyEvaluationContext.kt
- core/src/commonMain/kotlin/com/github/jcornaz/kwik/Runner.kt
- core/src/commonTest/kotlin/com/github/jcornaz/kwik/example/PlusOperatorTest.kt
- core/src/commonTest/kotlin/com/github/jcornaz/kwik/runner/AbstractRunnerTest.kt
- docs/built-in-generators.rst
- docs/write-tests.rst
> Add PropertyEvaluationContext and a way to skip an evaluation

- CHANGELOG.rst
- detekt-config.yml
- evaluator/src/commonMain/kotlin/com/github/jcornaz/kwik/evaluator/Evaluator.kt
- evaluator/src/commonTest/kotlin/com/github/jcornaz/kwik/evaluator/AbstractRunnerTest.kt
- evaluator/src/commonTest/kotlin/com/github/jcornaz/kwik/evaluator/ForAll1Test.kt
- evaluator/src/commonTest/kotlin/com/github/jcornaz/kwik/evaluator/ForAll2Test.kt
- evaluator/src/commonTest/kotlin/com/github/jcornaz/kwik/evaluator/ForAll3Test.kt
- evaluator/src/commonTest/kotlin/com/github/jcornaz/kwik/evaluator/ForAll4Test.kt
> Wrap exceptions thrown by the properties

- CHANGELOG.rst
- CONTRIBUTING.md
- README.rst
- build.gradle.kts
- docs/conf.py
> Document how to contribute

- CHANGELOG.rst
- docs/generators.rst
- generator/api/src/commonMain/kotlin/com/github/jcornaz/kwik/generator/api/Generator.kt
- generator/api/src/commonMain/kotlin/com/github/jcornaz/kwik/generator/api/GeneratorCombination.kt
- generator/stdlib/src/commonMain/kotlin/com/github/jcornaz/kwik/generator/stdlib/Collections.kt
- generator/stdlib/src/commonMain/kotlin/com/github/jcornaz/kwik/generator/stdlib/Sequences.kt
- generator/stdlib/src/commonTest/kotlin/com/github/jcornaz/kwik/generator/stdlib/SequenceGeneratorTest.kt
- generator/test/src/commonMain/kotlin/com/github/jcornaz/kwik/generator/test/AbstractGeneratorTest.kt
> Sequence generator

- CHANGELOG.rst
- docs/generators.rst
- generator/api/src/commonMain/kotlin/com/github/jcornaz/kwik/generator/api/Generator.kt
- generator/stdlib/src/jvmMain/kotlin/com/github/jcornaz/kwik/generator/stdlib/UUIDs.kt
- generator/stdlib/src/jvmTest/kotlin/com/github/jcornaz/kwik/generator/stdlib/UUIDGeneratorTest.kt
> Add a uuid generator

- CHANGELOG.rst
- build.gradle.kts
- docs/operators.rst
- generator/api/src/commonMain/kotlin/com/github/jcornaz/kwik/generator/api/GeneratorOperators.kt
- generator/api/src/commonTest/kotlin/com/github/jcornaz/kwik/generator/api/AndThenTest.kt
- gradle/wrapper/gradle-wrapper.properties
> Add andThen operator

- CHANGELOG.rst
- docs/operators.rst
- generator/api/src/commonMain/kotlin/com/github/jcornaz/kwik/generator/api/GeneratorCombination.kt
- generator/api/src/commonTest/kotlin/com/github/jcornaz/kwik/generator/api/FrequencyGeneratorTest.kt
> Add a frequency based combination of generator

- core/src/commonTest/kotlin/com/github/jcornaz/kwik/example/EnsureAtLeastOneTest.kt
- docs/write-tests.rst
- evaluator/src/commonMain/kotlin/com/github/jcornaz/kwik/evaluator/Evaluator.kt
- evaluator/src/commonMain/kotlin/com/github/jcornaz/kwik/evaluator/PropertyEvaluationContext.kt
- evaluator/src/commonTest/kotlin/com/github/jcornaz/kwik/evaluator/ForAll1Test.kt
It solves [issue#76](https://github.com/jcornaz/kwik/issues/76)
---
This pull request has been developed during [Open Source Saturday #30](https://www.meetup.com/it-IT/Open-Source-Saturday-Milano/events/266407734/) meetup in Milan.
[![Open Source Saturday](https://img.shields.io/badge/%E2%9D%A4%EF%B8%8F-open%20source%20saturday-F64060.svg)](https://www.meetup.com/it-IT/Open-Source-Saturday-Milano/)
> add ensureAtLeastOne assertion predicate

- core/src/commonTest/kotlin/com/github/jcornaz/kwik/example/EnsureAtLeastOneExample.kt
- evaluator/src/commonMain/kotlin/com/github/jcornaz/kwik/evaluator/Evaluator.kt
- evaluator/src/commonMain/kotlin/com/github/jcornaz/kwik/evaluator/PropertyEvaluationContext.kt
- evaluator/src/commonTest/kotlin/com/github/jcornaz/kwik/evaluator/ForAll1Test.kt
> Remove string key from ensureAtLeastOne

- .github/workflows/build.yml
- .github/workflows/publish.yml
- build.gradle.kts
- generator/stdlib/src/commonTest/kotlin/com/github/jcornaz/kwik/generator/stdlib/SequenceGeneratorTest.kt
- settings.gradle.kts
> Publish native artifacts to bintray

- .github/workflows/build.yml
- .github/workflows/check.yml
- .github/workflows/publish.yml
- build.gradle.kts
> Publish gh actions outputs

- CHANGELOG.rst
- evaluator/src/commonMain/kotlin/com/github/jcornaz/kwik/evaluator/FuzzerEvaluation.kt
- evaluator/src/commonMain/kotlin/com/github/jcornaz/kwik/evaluator/Simplification.kt
- evaluator/src/commonTest/kotlin/com/github/jcornaz/kwik/evaluator/ForAnyTest.kt
- evaluator/src/commonTest/kotlin/com/github/jcornaz/kwik/evaluator/SimplificationTest.kt
> Add input simplification (to the new fuzzer based API)

- fuzzer/api/src/commonMain/kotlin/com/github/jcornaz/kwik/simplifier/api/SimplifierFactory.kt
- fuzzer/api/src/commonTest/kotlin/com/github/jcornaz/kwik/simplifier/api/PairTest.kt
- fuzzer/api/src/commonTest/kotlin/com/github/jcornaz/kwik/simplifier/api/TripleTest.kt
Reduce the number of property evaluation necessary during simplification process, when simplifiers are combined.
> Optimize combined simplifiers

- .github/workflows/build.yml
- README.rst
- build.gradle.kts
- codecov.yml
> chore: Measure test code coverage

- .github/workflows/build.yml
- build.gradle.kts
- codecov.yml
- generator/api/src/commonMain/kotlin/com/github/jcornaz/kwik/generator/api/Generator.kt
Fix test code counting in coverage and change *patch* requirement
> chore: Fine tune coverage measure

- .github/semantic.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jcornaz/kwik/171)
> ci: Configure semantic pull-request check

- .github/workflows/build.yml
- README.rst
- package.json
(instead of 'master')
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jcornaz/kwik/172)
> chore: Update branch references to target 'main'

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jcornaz/kwik/176)
> chore: Add a stable release branch

- build.gradle.kts
- renovate.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jcornaz/kwik/178)
> chore: fine tune renovate config

- README.rst
- ROADMAP.md
Resolves #175 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jcornaz/kwik/180)
> docs: Add a roadmap

- build.gradle.kts
This only add the dokka plugin.
I will actually publish the result as part of the documentation after migration to kotlin 1.4 (#188)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jcornaz/kwik/155)
> chore: Add dokka plugin

- generator/stdlib/src/jvmMain/kotlin/com/github/jcornaz/kwik/generator/stdlib/DateTime.kt
- generator/stdlib/src/jvmTest/kotlin/com/github/jcornaz/kwik/generator/stdlib/DateTimeGeneratorTest.kt
Resolves #6 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jcornaz/kwik/181)
> feat: Add Duration/Instant/LocalTime generators

- .github/workflows/publish.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jcornaz/kwik/190)
> ci: Fix publication job
